# Generated by Django 4.0.6 on 2022-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='imgpromocion',
            field=models.ImageField(blank='', default='', upload_to='negocios/items/promociones/'),
        ),
    ]
