# Generated by Django 4.0.6 on 2022-10-19 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_imagen_alter_negocio_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='negocio',
            old_name='imagen',
            new_name='imgperfil',
        ),
        migrations.AddField(
            model_name='negocio',
            name='contactEmail',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='contactFacebook',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='contactInstagram',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='contactWEB',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='horaEntrada',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='horaSalida',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='negocio',
            name='imgportada',
            field=models.ImageField(blank='', default='', upload_to='negocios/'),
        ),
        migrations.AddField(
            model_name='negocio',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
