# Generated by Django 4.0.6 on 2022-10-21 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_imagen_negocio_imgperfil_negocio_contactemail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.negocio'),
        ),
    ]
